add validate.tsv for sv-SE
ftyers/commonvoice-utils pull request #12
Opened 2021-09-10 07:28 UTC by wenjie-p

2021-09-10 13:03 UTC, ftyers commented
Here is a description of the other commands:

* `LOWER` means turn everything to lowercase, for most Latin-based scripts you want to do this (your acoustic model shouldn't care about if something is `A` or `a`. 
* `NFKC` means normalise the Unicode encoding of combining characters, e.g. ä could be either `U+00E4` or `U+0061 U+0308`, this puts it into the canonical form. For Latin-based languages (apart from Vietnamese) you probably want this. In general, if the combining characters are representing tone, I leave them separate, if they are part of the glyph I use the precomposed ones where possible.
* `SKIP` if you see this symbol, skip the transcript, used for things like `+` where it isn't clear what the input or output could be (ideally Common Voice would not include these, but in any case I think they make no sense in training acoustic models)
* `NORM` is used for normalisations that you want to run, for example in English we can use some letters with diacritics like in *rôle*, *façade* and *naïve*, but for an acoustic model they would be too infrequent so I change them to *o*, *c* and *i* respectively. They can be restored in a postprocess if necessary/desired.

I'll start a review on the PR.

2021-09-10 13:21 UTC, ftyers requested changes
There are a couple of other things:
* Some characters are in the transcripts but not here, e.g. `ô`, I would use `NORM` to change it to `o`, it only appears once, but you might as well keep the transcript, and in future it might appear more.
* Some punctuation is missing, e.g. `”` (high frequency, definitely add it) and `…` and `—` (low frequency, but I'd add them anyway as the symbol list is not too long). 
* Add `LOWER` and `NFKC` at the top.

2021-09-10 13:21 UTC, ftyers commented on cvutils/data/sv-SE/validate.tsv
> +ALLOW	a	-	0x61	-
Other files have e.g. `0061` instead of `0x61`, it's just a comment but it would be good to have them consistent.

2021-09-10 13:21 UTC, ftyers commented on cvutils/data/sv-SE/validate.tsv
> +REPL	.	-	-	-
I would move `REPL` commands to the top (to be consistent with other files)

2021-09-10 15:43 UTC, wenjie-p commented on cvutils/data/sv-SE/validate.tsv
> +ALLOW	a	-	0x61	-
> * Some characters are in the transcripts but not here, e.g. `ô`, I would use `NORM` to change it to `o`, it only appears once, but you might as well keep the transcript, and in future it might appear more.

Sure, will add this item. I understand that diacritics only accompany with vowel letters, such as `a`, `u`, `o` and `e` in the `sv-SE`. Do you think it make sense to include all of them using the `Norm` command?

> * Some punctuation is missing, e.g. `”` (high frequency, definitely add it) and `…` and `—` (low frequency, but I'd add them anyway as the symbol list is not too long).

Sure, will add them.

> * Add `LOWER` and `NFKC` at the top.

OK.

2021-09-10 15:44 UTC, wenjie-p commented on cvutils/data/sv-SE/validate.tsv
> +REPL	.	-	-	-
> I would move `REPL` commands to the top (to be consistent with other files)

OK

2021-09-10 15:54 UTC, wenjie-p commented on cvutils/data/sv-SE/validate.tsv
> +ALLOW	a	-	0x61	-
> Other files have e.g. `0061` instead of `0x61`, it's just a comment but it would be good to have them consistent.

Actually, `0x61` was generated by the `Python` code : `hex(ord("a"))`, but I can change all the `0x**` with `00**` in this file.

2021-09-10 16:16 UTC, ftyers commented on cvutils/data/sv-SE/validate.tsv
> +ALLOW	a	-	0x61	-
> Sure, will add this item. I understand that diacritics only accompany with vowel letters, such as a, u, o and e in the sv-SE. Do you think it make sense to include all of them using the Norm command?

In Swedish the alphabet contains: `å`, `ä` and `ö`. The letter `é` is used in some integrated foreign words (*idé*, *armé* etc.) and in some surnames, e.g. *Huldén*:

* *Jag har nog **idéer**, men jag kan inte uttrycka dem.* "I have some ideas but I cannot express them"
 
I don't think it makes sense to include all possible diacritics, but we can include the ones that are already in the dataset, which is *ü* and *ô*:

* *Det ligger öster om **München** och är distriktets största samhälle.* "It lies east of Munich and is the district's largest settlement"
* *Jag bad honom komma och hämta mig på Grand **Hôtel** följande morgon.* "I asked him to come and fetch me in the Grand Hotel the following morning."

2021-09-10 23:05 UTC, wenjie-p commented
File update

2021-09-11 03:33 UTC, ftyers approved these changes
This looks great!

2021-09-11 03:34 UTC, merged

2021-09-11 03:37 UTC, ftyers commented
Oops, I just noticed (for future reference): The placeholders should be `_` not `-`. I made the change in 07fb058.